# Generated by Django 5.2.1 on 2025-05-17 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Тип оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('date', models.DateTimeField(max_length=100, verbose_name='Дата')),
                ('phone', models.CharField(max_length=100, verbose_name='Контактный номер телефона')),
                ('is_other', models.BooleanField(verbose_name='Другая услуга')),
                ('description', models.CharField(verbose_name='Описание услуги')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo2app.paymenttype', verbose_name='Тип оплаты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo2app.requesttype', verbose_name='Тип услуги')),
            ],
        ),
    ]
