# Generated by Django 5.2.1 on 2025-05-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo2app', '0002_requeststatus_alter_profile_user_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reject_message',
            field=models.CharField(default='', verbose_name='Причина отмены'),
        ),
    ]
