# Generated by Django 5.2.1 on 2025-05-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo2app', '0004_alter_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.CharField(blank=True, null=True, verbose_name='Описание услуги'),
        ),
    ]
