# Generated by Django 5.2.1 on 2025-05-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo2app', '0005_alter_request_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='reject_message',
            field=models.CharField(blank=True, default='', null=True, verbose_name='Причина отмены'),
        ),
    ]
